services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    environment:
      ConnectionStrings__Database: Host=bookify-db;Port=5432;Database=bookify;Username=postgres;Password=postgres;
      ConnectionStrings__Cache: bookify-redis:6379
      Serilog__WriteTo__1__Args__serverUrl: http://bookify-seq:5341
      Authentication__ValidIssuer: http://bookify-idp:8080/realms/bookify
      Authentication__MetadataUrl: http://bookify-idp:8080/realms/bookify/.well-known/openid-configuration
      Keycloak__BaseUrl: http://bookify-idp:8080
      Keycloak__AdminUrl: http://bookify-idp:8080/admin/realms/bookify/
      Keycloak__TokenUrl: http://bookify-idp:8080/realms/bookify/protocol/openid-connect/token
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
      - bookify-db
      
  bookify-db:
    image: postgres:17
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432

  bookify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Bookify.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080
      
  bookify-seq:
    image: datalust/seq:latest
    container_name: Bookify.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - 5341:5341
      - 8081:80

  bookify-redis:
    image: redis:latest
    container_name: Bookify.Redis
    restart: always
    ports:
      - '6379:6379'
      
volumes:
  postgres-data: